### ISSUE TITLE
table of before/after

### ISSUE THREAD

**Issue by rachelss** [anprita/homework-r#2]
You can use the html table but use inline code for the number of individuals. If the data changes so will the output. 

Alternatively use kable - see 
https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html
https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf

**Comment by anprita** [comment]
Thank you Dr. Rachel, 
We've already change the html table into kable. 
Please take a look.
